### PR TITLE
Filled in basic structure for signup page. CSS styling to be added later

### PR DESCRIPTION
**Pull request by Ida-Whit**
Filled in basic structure for signup page. CSS styling to be added later

### CODE REVIEW

**Review by CRNaro — APPROVED** [review]
LGTM

**Review by CRNaro — CHANGES_REQUESTED** [review]
There seems to be a conflict.  I cant seem to fix it on my end for some reason.  Can you just take a look at it?

**Review by hwoolford — APPROVED** [review]

**Review by Ida-Whit — COMMENTED** [review]
Fixed

**Review by CRNaro — APPROVED** [review]
LGTM?

**Pull request merged**
